CREATE DATABASE IF NOT EXISTS crm_jdl;
USE crm_jdl;

CREATE TABLE IF NOT EXISTS crm_app_state (
  id TINYINT UNSIGNED PRIMARY KEY,
  state_json LONGTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
